version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Go modules
  - package-ecosystem: "gomod"
    directories:
      - "/operator"
      - "/dbaas-adapter"
    schedule:
      interval: "weekly"

  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directories:
      - "/integration-tests/docker"
      - "/monitoring/docker/config"
      - "/curator/opensearch_indices_cleaner/docker"
    schedule:
      interval: "weekly"

  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/docker-opensearch/opensearch-filter-plugin"
    schedule:
      interval: "weekly"

  # Docker images
  - package-ecosystem: "docker"
    directories:
      - "/operator"
      - "/docker-transfer"
      - "/tls-init/docker"
      - "/operator/dev-kit"
      - "/monitoring/docker"
      - "/dbaas-adapter/docker"
      - "/docker-opensearch/docker"
      - "/integration-tests/docker"
      - "/curator/docker/backup-docker"
      - "/curator/opensearch_indices_cleaner/docker"
    schedule:
      interval: "weekly"
