{{- $secretName := include "curator.s3.tlsSecretName" . }}
{{- if and $secretName .Values.opensearch.snapshots.s3.enabled .Values.opensearch.snapshots.s3.sslCert }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  ca.crt: {{ .Values.opensearch.snapshots.s3.sslCert | quote }}
{{- end }}