---

name: Helm Charts Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: read

run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          tag-name: '${{ inputs.release }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  load-docker-build-components:
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.load_component.outputs.components }}
      platforms: ${{ steps.load_component.outputs.platforms }}
    env:
      CONFIG_FILE: .qubership/docker-build-config.cfg
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Load Docker Configuration
        id: load_component
        run:  |
          verify=$(cat "$GITHUB_WORKSPACE/${CONFIG_FILE}" | jq '
          def verify_structure:
          .components as $components
          | .platforms as $platforms
          | ($components | type == "array")
          and (all($components[]; has("name") and has("file") and has("context")))
          and ($platforms | type == "string");
          verify_structure
          | if . then true else false end
          ')
          if [ ${verify} == 'true' ]; then
            echo "✅ $GITHUB_WORKSPACE/${CONFIG_FILE} file is valid"
            components=$(jq -c ".components" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/${CONFIG_FILE}")
          else
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid"
            echo "❗ $GITHUB_WORKSPACE/${CONFIG_FILE} file is invalid" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          echo "components=${components}" >> $GITHUB_OUTPUT
          echo "platforms=${platforms}" >> $GITHUB_OUTPUT

  docker-check-build:
    needs: [load-docker-build-components, check-tag]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    steps:
      - name: Get version for current component
        id: get-version
        run: |
          echo "IMAGE=${{ matrix.component.name }}" >> $GITHUB_ENV
      - name: Docker build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          ref: ${{ github.ref }}
          download-artifact: false
          dry-run: true
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
          tags: "${{ env.IMAGE_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  chart-release-prepare:
    permissions:
      contents: write
      packages: write
    needs: [check-tag, load-docker-build-components, docker-check-build]
    runs-on: ubuntu-latest
    outputs:
      images-versions: ${{ steps.update-versions.outputs.images-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: "Add github.vars into github.env"
        env:
          VARS_JSON: '${{ toJson(vars) }}'
        run: |
          echo "${VARS_JSON}" | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >> $GITHUB_ENV

      - name: "Update versions in values"
        id: update-versions
        uses: netcracker/qubership-workflow-hub/actions/charts-values-update-action@b6d2198c722564e250d985a99990230d85b0d686  # v2.0.3
        with:
          release-version: ${{ inputs.release }}
          config-file: .github/charts-values-update-config.yaml

      - name: "Debug"
        env:
          IMAGES_VERSIONS: '${{ steps.update-versions.outputs.images-versions }}'
        run: |
          echo "Images versions: ${IMAGES_VERSIONS}"

  docker-build:
    permissions:
      contents: write
      packages: write
    needs: [chart-release-prepare, load-docker-build-components]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    steps:
      - name: Get version for current component
        id: get-version
        env:
          IMG_VER: '${{ fromJson(needs.chart-release-prepare.outputs.images-versions)[matrix.component.name] || inputs.release }}'
        run: |
          echo "IMAGE_VERSION=${IMG_VER}" >> $GITHUB_ENV

      - name: Docker build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          ref: release-${{ inputs.release }}
          download-artifact: false
          dry-run: false
          component: ${{ toJson(matrix.component) }}
          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
          tags: "${{ env.IMAGE_VERSION }},latest"
        env:
          GITHUB_TOKEN: ${{ github.token }}
  charts-release:
    permissions:
      contents: write
      packages: write
    needs: [docker-build]
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0
          ref: release-${{ inputs.release }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        #continue-on-error: true
        uses: netcracker/chart-releaser-action@7015249576e76bfb228e6fe04b4869d44511c014  # main
        with:
          charts_dir: operator/charts/helm
          release_name_template: "{{ .Version }}"
          skip_existing: true
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Release-drafter"
        uses: netcracker/release-drafter@86f4276a3894b5af70480e826c32fe3648ac6a70  # v1.0.0
        with:
          config-name: release-drafter-config.yml
          publish: true
          name: ${{ inputs.release }}
          tag: ${{ inputs.release }}
          version: ${{ inputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Assets
        uses: netcracker/qubership-workflow-hub/actions/assets-action@396774180000abdb825cbf150b56cc59c6913db8  # v2.0.5
        with:
          tag: ${{ inputs.release }}
          item-path: .cr-release-packages/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
