name: Run Opensearch Pipeline

permissions:
  contents: read

on:
   pull_request:
     types: [opened, synchronize, reopened]
     branches: [main]

jobs:
  start-self-hosted-runner:
    uses: Netcracker/qubership-terraform-hub/.github/workflows/ec2-control.yml@main
    with:
      instance_id: ${{ vars.AWS_GITHUB_RUNNER_ID }}
      action: 'start'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Opensearch-Pipeline:
    needs: start-self-hosted-runner
    uses: Netcracker/qubership-test-pipelines/.github/workflows/opensearch.yaml@e75a24c6a1e5d843de60674e9a395ecb003f5cf3
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      versions_file: '.github/versions.yaml'
      pipeline_branch: 'e75a24c6a1e5d843de60674e9a395ecb003f5cf3' #this value must match the value after '@' in 'uses'
      runner_type: 'self-hosted'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}

  stop-self-hosted-runner:
    needs: Opensearch-Pipeline
    if: always()
    uses: Netcracker/qubership-terraform-hub/.github/workflows/ec2-control.yml@main
    with:
      instance_id: ${{ vars.AWS_GITHUB_RUNNER_ID }}
      action: 'stop'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
